name: Renovate

on:
  schedule:
   - cron: "*/2 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run Renovate
        uses: renovatebot/renovate@v35.131.0
      - name: Enable Automerge Action
        uses: daneden/enable-automerge-action@v1.0.2


        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Add any additional configuration options here
          
